name: adelineseidel
favicon: null
layout_spectrum: 0.75126
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8c9aa4'
    - '#f7f7f7'
    - '#151515'
    - '#6f3739'
    - '#da8178'
  brandStrength: 0.6875
  lightness: 0.9721816312521696
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
